import type { ScenarioCardData } from "@/features/dashboard/types/scenario-cards.types";

export const SCENARIO_CARDS_DATA: ScenarioCardData[] = [
  {
    id: 1,
    topBorderColor: "border-t-[#0E6A37]",
    badgeText: "Current State",
    badgeBg: "bg-[#E7F0EB]",
    badgeTextColor: "text-[#0E6A37]",
    title: "Current State",
    subtitle: "Your Current Capacity Setup",
    metricsColor: "text-[#0E6A37]",
    metrics: {
      stranded: "62%",
      wasted: "6.2MV",
      financial: "$1.24M-$1.68M",
    },
    score: "B-",
    scoreStatus: "Moderate",
    scoreBadgeBg: "bg-[#FEE2E2]",
    scoreBadgeTextColor: "text-[#DC2626]",
  },
  {
    id: 2,
    topBorderColor: "border-t-[#0284C7]",
    badgeText: "Scenario 1",
    badgeBg: "bg-[#E0F2FE]",
    badgeTextColor: "text-[#0284C7]",
    title: "Optimized Cooling",
    subtitle: "Upgrade to liquid cooling System",
    metricsColor: "text-[#0284C7]",
    metrics: {
      stranded: "38%",
      wasted: "3.8MV",
      financial: "$0.76M-$1.04M",
    },
    score: "B+",
    scoreStatus: "Good",
    scoreBadgeBg: "bg-[#E7F0EB]",
    scoreBadgeTextColor: "text-[#0E6A37]",
  },
  {
    id: 3,
    topBorderColor: "border-t-[#F97316]",
    badgeText: "Scenario 2",
    badgeBg: "bg-[#FFEDD5]",
    badgeTextColor: "text-[#F97316]",
    title: "Improve Utilization",
    subtitle: "Increase utilization to 80%",
    metricsColor: "text-[#F97316]",
    metrics: {
      stranded: "42%",
      wasted: "4.2MV",
      financial: "$0.88M-$1.20M",
    },
    score: "B",
    scoreStatus: "Moderate",
    scoreBadgeBg: "bg-[#FEF3C7]",
    scoreBadgeTextColor: "text-[#D97706]",
  },
];