name: Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches: ['*']
    paths:
      - 'client/**'

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with: 
          fetch-depth: 0

      - name: Type Check
        uses: actions/setup-node@670825a89dc0abd596e7a3abd0f5e3f6e5faf37c
        with:
          node-version: 20
      - run: npm ci
      - run: npx tsc -b --noEmit